from pydantic import BaseModel, Field

class ChargeOff(BaseModel):
    loan_amnt:float = Field(example=2000)
    purpose:str = Field(example='wedding')
    fico:float = Field(example = 800)
    dti:float = Field(example = 1)
    addr_state:str = Field(example = 'CA')
    emp_length:float = Field(example = 10)
    
class Grade(BaseModel):
    loan_amnt:float = Field(example = 4575)
    term:int = Field(example = 36)
    emp_length:float = Field(example = 10)
    home_ownership:str = Field(example = 'MORTGAGE')
    annual_inc:float = Field(example = 4.716011695371454)
    verification_status:str = Field(example = 'Source Verified')
    purpose:str = Field(example = 'debt_consolidation')
    addr_state:str = Field(example = 'AZ')
    dti:float = Field(example = 29.74)
    pub_rec:float = Field(example = 0)
    total_acc:float = Field(example = 12)
    initial_list_status:str = Field(example = 'w')
    application_type:str = Field(example = 'Individual')
    mo_sin_old_il_acct:float = Field(example = 157)
    mo_sin_old_rev_tl_op:float = Field(example = 71)
    mort_acc:float = Field(example = 2)
    fico:float = Field(example = 672)

class Sub_grade(BaseModel):
    loan_amnt:float = Field(example = 4575)
    term:int = Field(example = 36)
    grade:str = Field(example = 'C')
    emp_length:float = Field(example = 10)
    home_ownership:str = Field(example = 'MORTGAGE')
    annual_inc:float = Field(example = 4.716011695371454)
    verification_status:str = Field(example = 'Source Verified')
    purpose:str = Field(example = 'debt_consolidation')
    addr_state:str = Field(example = 'AZ')
    dti:float = Field(example = 29.74)
    pub_rec:float = Field(example = 0)
    total_acc:float = Field(example = 12)
    initial_list_status:str = Field(example = 'w')
    application_type:str = Field(example = 'Individual')
    mo_sin_old_il_acct:float = Field(example = 157)
    mo_sin_old_rev_tl_op:float = Field(example = 71)
    mort_acc:float = Field(example = 2)
    fico:float = Field(example = 672)

class Int_rate(BaseModel):
    loan_amnt:float = Field(example = 4575)
    term:int = Field(example = 36)
    grade:str = Field(example = 'C')
    sub_grade:str = Field(example = 'C2')
    emp_length:float = Field(example = 10)
    home_ownership:str = Field(example = 'MORTGAGE')
    annual_inc:float = Field(example = 4.716011695371454)
    verification_status:str = Field(example = 'Source Verified')
    purpose:str = Field(example = 'debt_consolidation')
    addr_state:str = Field(example = 'AZ')
    dti:float = Field(example = 29.74)
    pub_rec:float = Field(example = 0)
    total_acc:float = Field(example = 12)
    initial_list_status:str = Field(example = 'w')
    application_type:str = Field(example = 'Individual')
    mo_sin_old_il_acct:float = Field(example = 157)
    mo_sin_old_rev_tl_op:float = Field(example = 71)
    mort_acc:float = Field(example = 2)
    fico:float = Field(example = 672)